CREATE DATABASE QuanLyChoThueToChucSuKien3;
GO
USE QuanLyChoThueToChucSuKien3;
GO

-- Tạo bảng KhachHang
CREATE TABLE KhachHang (
    MaKH VARCHAR(10) CONSTRAINT PK_KhachHang PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255),
    SoDienThoai VARCHAR(15),
    Email NVARCHAR(100)
);

-- Tạo bảng HopDong
CREATE TABLE HopDong (
    MaHD VARCHAR(10) CONSTRAINT PK_HopDong PRIMARY KEY,
    MaKH VARCHAR(10) NOT NULL,
    NgayKyKet DATE NOT NULL,
    TongTien DECIMAL(18, 2) NOT NULL,
    TrangThaiHopDong NVARCHAR(50),
    MaSK VARCHAR(10) UNIQUE, -- Each HopDong may reference one SuKien
    CONSTRAINT FK_HopDong_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

-- Tạo bảng SuKien
CREATE TABLE SuKien (
    MaSK VARCHAR(10) CONSTRAINT PK_SuKien PRIMARY KEY,
    MaHD VARCHAR(10) NOT NULL UNIQUE, -- Each SuKien must reference one HopDong
    TenSuKien NVARCHAR(100) NOT NULL,
    NgayToChuc DATE NOT NULL,
    NgayKetThuc DATE,
    DiaDiem NVARCHAR(255),
    MoTa NVARCHAR(1000),
    CONSTRAINT FK_SuKien_HopDong FOREIGN KEY (MaHD) REFERENCES HopDong(MaHD)
);

-- Tạo bảng DichVu
CREATE TABLE DichVu (
    MaDV VARCHAR(10) CONSTRAINT PK_DichVu PRIMARY KEY,
    TenDV NVARCHAR(100) NOT NULL,
    DonGia DECIMAL(18, 2),
    MoTa NVARCHAR(1000),
    DonViTinh NVARCHAR(50),
    TinhTrang NVARCHAR(50)
);

-- Tạo bảng ChiTietDichVuHopDong
CREATE TABLE ChiTietDichVuHopDong (
    MaHD VARCHAR(10) NOT NULL,
    MaDV VARCHAR(10) NOT NULL,
    SoLuong INT NOT NULL,
    DonGia DECIMAL(18, 2),
    ThanhTien AS (SoLuong * DonGia) PERSISTED,
    CONSTRAINT PK_ChiTietDichVuHopDong PRIMARY KEY (MaHD, MaDV),
    CONSTRAINT FK_CT_DVHD_HopDong FOREIGN KEY (MaHD) REFERENCES HopDong(MaHD),
    CONSTRAINT FK_CT_DVHD_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV)
);

-- Tạo bảng Loa
CREATE TABLE Loa (
    MaLoa VARCHAR(10) CONSTRAINT PK_Loa PRIMARY KEY,
    MaDV VARCHAR(10) NOT NULL,
    LoaiLoa NVARCHAR(100),
    CongSuat DECIMAL(18, 2),
    CONSTRAINT FK_Loa_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV)
);

-- Tạo bảng Den
CREATE TABLE Den (
    MaDen VARCHAR(10) CONSTRAINT PK_Den PRIMARY KEY,
    MaDV VARCHAR(10) NOT NULL,
    LoaiDen NVARCHAR(100),
    CongSuat DECIMAL(18, 2),
    CONSTRAINT FK_Den_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV)
);

-- Tạo bảng NhaBanhU
CREATE TABLE NhaBanhU (
    MaNhaBanhU VARCHAR(10) CONSTRAINT PK_NhaBanhU PRIMARY KEY,
    MaDV VARCHAR(10) NOT NULL,
    DienTich DECIMAL(18, 2),
    CONSTRAINT FK_NhaBanhU_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV)
);

-- Tạo bảng NhaTienChe
CREATE TABLE NhaTienChe (
    MaNhaTienChe VARCHAR(10) CONSTRAINT PK_NhaTienChe PRIMARY KEY,
    MaDV VARCHAR(10) NOT NULL,
    DienTich DECIMAL(18, 2),
    CONSTRAINT FK_NhaTienChe_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV)
);

-- Tạo bảng CongHoiCho
CREATE TABLE CongHoiCho (
    MaCongHoiCho VARCHAR(10) CONSTRAINT PK_CongHoiCho PRIMARY KEY,
    MaDV VARCHAR(10) NOT NULL,
    LoaiCong NVARCHAR(100),
    CONSTRAINT FK_CongHoiCho_DichVu FOREIGN KEY (MaDV) REFERENCES DichVu(MaDV)
);

-- Tạo bảng ThanhToan
CREATE TABLE ThanhToan (
    MaThanhToan VARCHAR(10) CONSTRAINT PK_ThanhToan PRIMARY KEY,
    MaHD VARCHAR(10) NOT NULL,
    SoTien DECIMAL(18, 2),
    NgayThanhToan DATE NOT NULL,
    PhuongThuc NVARCHAR(100),
    TrangThai NVARCHAR(50),
    CONSTRAINT FK_ThanhToan_HopDong FOREIGN KEY (MaHD) REFERENCES HopDong(MaHD)
);

-- Tạo bảng NhanSu
CREATE TABLE NhanSu (
    MaNS VARCHAR(10) CONSTRAINT PK_NhanSu PRIMARY KEY,
    TenNS NVARCHAR(100),
    ChucVu NVARCHAR(50),
    SoDienThoai NVARCHAR(15),
    Email NVARCHAR(100)
);

-- Tạo bảng PhanCong
CREATE TABLE PhanCong (
    MaPhanCong VARCHAR(10) CONSTRAINT PK_PhanCong PRIMARY KEY,
    MaHD VARCHAR(10) NOT NULL,
    MaNS VARCHAR(10) NOT NULL,
    VaiTro NVARCHAR(100),
    CONSTRAINT FK_PhanCong_HopDong FOREIGN KEY (MaHD) REFERENCES HopDong(MaHD),
    CONSTRAINT FK_PhanCong_NhanSu FOREIGN KEY (MaNS) REFERENCES NhanSu(MaNS)
);
